config/routes.rb
Rails.application.routes.draw do
  devise_for :users  , :path_prefix => 'my', :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'login', to: 'devise/session#new'
  end
  resources :users
  delete 'users/:id/edit', to: 'users#delete'
 
  get 'informes/index'
  get 'informes/new'
  resources :informacion
  resources :facultads
  delete 'facultads/:id/edit', to: 'facultads#delete'
  resources :alertas
  resources :estudiantes
  delete 'estudiantes/:id/edit', to: 'estudiantes#delete'
  resources :informes
  delete 'informes/:id/edit', to: 'informes#delete'
  resources :rols
  resources :tutores
  delete 'tutores/:id/edit', to: 'tutores#delete'
  resources :carreras
  delete 'carreras/:id/edit', to: 'carreras#delete'
  resources :page

  

  devise_scope :user do
    authenticated :user do
      root 'page#index', as: :authenticated_root
    end
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end



  




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/informe.rb
class Informe < ApplicationRecord
  has_one :alerta
  belongs_to :estudiante
  belongs_to :user
  validates :nota1,:nota2,:nota3 ,:nota4,:nota5,:nota6,:nota7,:nota8,:nota9,:nota10,:nota11,:nota12,:nota13,:nota14,:nota15,:nota16,:nota17,:nota18,:nota19,:nota20,:nota21,:nota22,:nota23,:nota24,:nota25,:nota26,:nota27,:nota28,  :presence => true

end

app/controllers/informes_controller.rb
class InformesController < ApplicationController
  layout"prueba"
  before_action :set_informe, only: [:show,:delete,:edit,:update]
  
  
  def index
    @informes=Informe.all
    @alertas= Alerta.all
  
    
  end

  def show
    @informe= Informe.find(params[:id])
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'informes/reporte', pdf:'Reporte'}

    end
  end

  def new
    @informes= Informe.new
    @alertas= Alerta.new
  end
  
  def delete
    #@user.destroy
    
    @informe.estado = false
    @informe.save
      redirect_to informes_path, success: "Informe inactivo"
      
  
  end
  
  def update
    if @informe.update(informe_params)
      redirect_to informe_path, success: "Se Actualizaron los datos"
    else
      render :edit, danger: "Modifique por valores válidos"
    end
  end


  def create
      @informe = Informe.new(informe_params)
      @informe.user_id=current_user.id
      if @informe.save
      
          #if(@informe.nota1==1 && @informe.nota2==0 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==1 && @informe.nota6==1 && @informe.nota7==0 && @informe.nota8==1 && @informe.nota9==0 && @informe.nota10==1 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==0 && @informe.nota15==0 && @informe.nota16==1 && @informe.nota17==0 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==0 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
          if @informe.nota10==1 
          @informe.resultado="Gerente General de Empresa de Finanzas"
          end
         
          if(@informe.nota1==1 && @informe.nota2==0 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==1 && @informe.nota6==1 && @informe.nota7==0 && @informe.nota8==1 && @informe.nota9==0 && @informe.nota10==1 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==0 && @informe.nota15==0 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==0 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Gerente General de Empresa de Retail"
          end
         
          
          if(@informe.nota1==1 && @informe.nota2==1 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==1 && @informe.nota6==1 && @informe.nota7==1 && @informe.nota8==1 && @informe.nota9==1 && @informe.nota10==1 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==1 && @informe.nota15==1 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==0 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Gerente General de Empresa de Tecnologías de la Información"
          end

          if(@informe.nota1==1 && @informe.nota2==0 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==1 && @informe.nota6==1 && @informe.nota7==0 && @informe.nota8==1 && @informe.nota9==1 && @informe.nota10==1 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==1 && @informe.nota15==0 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==0 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Gerente General de Empresa de Transportes"
          end

          if(@informe.nota1==1 && @informe.nota2==1 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==1 && @informe.nota6==0 && @informe.nota7==1 && @informe.nota8==1 && @informe.nota9==1 && @informe.nota10==1 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==0 && @informe.nota15==1 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==0 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Gerente General de Empresa de RRHH"
          end

          if(@informe.nota1==1 && @informe.nota2==1 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==0 && @informe.nota6==1 && @informe.nota7==0 && @informe.nota8==1 && @informe.nota9==1 && @informe.nota10==1 && @informe.nota11==1 && @informe.nota12==0 && @informe.nota13==1 && @informe.nota14==1 && @informe.nota15==1 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==0 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Dueño absoluto de una empresa"
          end







          
          if(@informe.nota1==1 && @informe.nota2==1 && @informe.nota3==1 && @informe.nota4==0 && @informe.nota5==1 && @informe.nota6==1 && @informe.nota7==1 && @informe.nota8==0 && @informe.nota9==1 && @informe.nota10==0 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==1 && @informe.nota15==1 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==1 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Gerente Funcional de Departamento de Compras"
          end

          if(@informe.nota1==1 && @informe.nota2==1 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==1 && @informe.nota6==1 && @informe.nota7==1 && @informe.nota8==0 && @informe.nota9==1 && @informe.nota10==0 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==1 && @informe.nota15==1 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==1 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Gerente Funcional de Ventas"
          end

          if(@informe.nota1==1 && @informe.nota2==1 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==0 && @informe.nota6==1 && @informe.nota7==1 && @informe.nota8==0 && @informe.nota9==1 && @informe.nota10==0 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==1 && @informe.nota15==1 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==1 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Gerente Funcional de RRHH"
          end



          if(@informe.nota1==1 && @informe.nota2==0 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==1 && @informe.nota6==1 && @informe.nota7==1 && @informe.nota8==0 && @informe.nota9==1 && @informe.nota10==0 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==1 && @informe.nota15==1 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==1 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Administrador de Departamento"
          end


          if(@informe.nota1==1 && @informe.nota2==0 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==1 && @informe.nota6==1 && @informe.nota7==1 && @informe.nota8==0 && @informe.nota9==1 && @informe.nota10==0 && @informe.nota11==0 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==1 && @informe.nota15==1 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==1 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Administrador de Retail"
          end

          if(@informe.nota1==1 && @informe.nota2==1 && @informe.nota3==1 && @informe.nota4==1 && @informe.nota5==1 && @informe.nota6==1 && @informe.nota7==1 && @informe.nota8==0 && @informe.nota9==1 && @informe.nota10==0 && @informe.nota11==1 && @informe.nota12==1 && @informe.nota13==1 && @informe.nota14==1 && @informe.nota15==1 && @informe.nota16==1 && @informe.nota17==1 && @informe.nota18==0 && @informe.nota19==1 && @informe.nota20==1 && @informe.nota21==1 && @informe.nota22==0 && @informe.nota23==1 && @informe.nota24==1 && @informe.nota25==1 && @informe.nota26==0 && @informe.nota27==1 && @informe.nota28==0 )
            @informe.resultado="Jefe de Proyectos"
          end
          
          

app/helpers/informes_helper.rb
module InformesHelper
end

app/views/informes/index.html.erb
<h1>Perfiles <% if current_user.rol.descripcion!='Administrador'%><%= current_user.rol.descripcion%><%end%></h1>
<%= link_to 'Generar Perfil', new_informe_path, :class => "btn btn-info" %>
<Table class="table">
  <tr>
    <thead class="thead-dark">
   
    <th> Nombre Trabajador </th>
    
    <th> Cargo Asignado</th>
    
    <th> Opciones </th>
  </thead>
  </tr>

  <% @informes.each do |t| %>
  
 <% if t.estado == true %>
  <tr>
  
  <td><%= t.estudiante.nombreestudiante %> <%= t.estudiante.apellidopa %> <%= t.estudiante.apellidoma %></td>
  <td><%= t.resultado %>
  

  </td>
  <td>
  <%= link_to 'Mostrar', informe_url(t), class:"btn btn-outline-success  btn-sm" %>


    
	<% unless t.estado.nil? %>
	<% if t.estado == true %>
			
	  <%= link_to 'Eliminar', edit_informe_url(t), class: "btn btn-danger btn-sm",
                        method: :delete, data: {confirm: '¿Estas seguro?'} %>
    <% end %>
	  <% end %>
</td>
</tr>
<% end %>
<%end%>
</table>

app/views/informes/new.html.erb
<%flash.each do |name , msg| %>
  <div class="alert alert-<%= name %>">
    <%= msg %>
  </div>
<% end %>



<center><h1 class= text-info ><u> Perfil </u></h1><br></center>


<%=form_for( @informes) do |f| %>
  <label class="text-dark"><u>Emitido por :</u> <%=current_user.nombre%> <%=current_user.apellidopa%> <%=current_user.apellidoma%></label>
  <br><br><label class="text-dark"><u>Trabajador</u></label>

  <%= f.collection_select :estudiante_id, Estudiante.all, :id,:fullname, {:include_blank => "Seleccionar Trabajador"},{class: "btn btn-outline-info btn-sm"}  %>
 <br><br>
 
 
<table class="table">
<thead class ="thead-info">
<tr>
<th scope="col">Preguntas</th>
<th scope="col">Respuestas</th>
</tr>
    
<tbody>
 <tr>

     <td>  <label class="text-dark text-justify"><li>1.)¿Es capaz de sacar conclusiones detalladas de un texto o problema?</li></label></td>
      <td>  <%= f.collection_radio_buttons:nota1,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>     
 
 <tr>
 <td>  <label class="text-dark text-justify"><li> 2.)¿Usted mantiene siempre buenas relaciones con sus compañeros de trabajo?</li></label></td>
  <td>  <%= f.collection_radio_buttons:nota2,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
  </tr>
  <tr>
 <td>  <label class="text-dark text-justify"><li> 3.)¿Se toma en serio una competencia entre amigos?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota3,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>
 <tr>
 <td>  <label class="text-dark text-justify"><li> 4.)¿Si una persona necesita información, usted estaría totalmente dispuesto a ayudarle con una explicación detallada?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota4,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>
 
 <tr>
 <td>  <label class="text-dark text-justify"><li>5.)¿En una situación de conflicto, estaría dispuesto a mediar para solucionarlo?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota5,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>6.)¿Usted realiza sus actividades de forma ordenada y a la misma hora?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota6,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>7.)¿En una situación de descontrol emocional de un amigo o compañero, usted intenta contenerlo?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota7,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>8.)¿Le emocionan los nuevos proyectos?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota8,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>9.)¿Usted gusta de las sorperesas?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota9,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>




 <tr>
 <td>  <label class="text-dark text-justify"><li>10.)¿Sus decisiones en la mayoría de los casos van orientadas a una visión futura?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota10,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>


 <tr>
 <td>  <label class="text-dark text-justify"><li>11.)¿En una actividad grupal, considera que la opinión de todos importa?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota11,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>12.)¿Le agrada cumplir con sus trabajos sin falta?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota12,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>13.)¿Usted tiene conocimientos nivel usuario de computación, es bueno en matemáticas?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota13,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>14.)¿Usted considera que tiene conocimientos acabados en su área de especialidad?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota14,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>
 <tr>
 <td>  <label class="text-dark text-justify"><li>15.)¿le agrada el trabajo en equipo? </li></label></td>
 <td>  <%= f.collection_radio_buttons:nota15,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>16.)¿Es bueno planificando y prediciendo situaciones? </li></label></td>
 <td>  <%= f.collection_radio_buttons:nota16,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>17.)¿Le agradan los procedimientos ordenados?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota17,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>



 <tr>
 <td>  <label class="text-dark text-justify"><li>18.)¿Le gusta hacer actividades productivas en horas libres?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota18,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>19.)¿Se siente comodo aceptando gran responsabilidad por un proyecto?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota19,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>20.)¿Usted siempre termina lo que empieza?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota20,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>21.)¿Puede dejar un trabajo sin terminar?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota21,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>22.)¿Siente inseguridad si no tiene un grupo que le apoye?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota22,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>23.)¿Le gusta ser parte de un grupo?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota23,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>24.)¿Le gusta tener estimulos que lo motiven a continuar?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota24,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>25.)¿Considera que esta sociedad es muy individualista?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota25,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>26.)¿Considera que en esta sociedad las personas trabajan en equipo?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota26,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>27.)¿Considera que existe en esta sociedad competencia por puestos de trabajo?</label></td>
 <td>  <%= f.collection_radio_buttons:nota27,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>

 <tr>
 <td>  <label class="text-dark text-justify"><li>28.)¿Considera que encontrar trabajo en esta sociedad es sencillo?</li></label></td>
 <td>  <%= f.collection_radio_buttons:nota28,[[1,'Si.....'],[0,'No']],:first,:last,{},{:class => "create-proyect"} %> </td>
 </tr>









  </tr>   






  </table>
  
      <%= f.submit "Guardar" ,class:"btn btn-info" %>
     
<%end%>




  