config/routes.rb
Rails.application.routes.draw do
  devise_for :users  , :path_prefix => 'my', :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'login', to: 'devise/session#new'
  end
  resources :users
  delete 'users/:id/edit', to: 'users#delete'
 
  get 'informes/index'
  get 'informes/new'
  resources :informacion
  resources :facultads
  delete 'facultads/:id/edit', to: 'facultads#delete'
  resources :alertas
  resources :estudiantes
  delete 'estudiantes/:id/edit', to: 'estudiantes#delete'
  resources :informes
  delete 'informes/:id/edit', to: 'informes#delete'
  resources :rols
  resources :tutores
  delete 'tutores/:id/edit', to: 'tutores#delete'
  resources :carreras
  delete 'carreras/:id/edit', to: 'carreras#delete'
  resources :page

  

  devise_scope :user do
    authenticated :user do
      root 'page#index', as: :authenticated_root
    end
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end



  




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :estudiantes, optional:true
  belongs_to :facultad, optional:true
  belongs_to :rol, optional:true
  
  
  validates :estado, :inclusion => {:in=> [true,false]}
  validates :nombre, presence:  { message: 'Ingrese el primer nombre '} , length: {in: 3..40, message:'El nombre debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z\s]+\z/,
  message: "Se permiten solo letras en los nombres"}
  validates :apellidopa, presence: { message: 'Ingrese el primer apellido'}, length: {in: 3..20, message:'El apellido debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z\s]+\z/,message: "Se permiten solo letras en los apellidos"}
  validates :apellidoma, presence: { message: 'Ingrese el segundo apellido'}, length: {in: 3..20, message:'El apellido debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z\s]+\z/, message: "Se permiten solo letras en los apellidos"}
  include RunCl::ActAsRun
  Run.valid? '11.1111.111-1'
  Run.format('11.111.111-1')
  validates :rut , presence: { message: 'Ingrese un rut'}, uniqueness: true
  has_run_cl :rut
 validate :unique_rut
validates :fecha_nacimiento , presence: {message: 'Ingrese la fecha de nacimiento'}
validates :telefono, presence: {message: 'Ingrese Telefono'}, length: {is: 9, message:'Largo debe ser 9'}
validate :fecha_de_nacimiento_debe_ser_en_pasado
validate :edadminima



def fecha_de_nacimiento_debe_ser_en_pasado
  if fecha_nacimiento.present? && fecha_nacimiento >= Date.today
  errors.add(:fecha_nacimiento, "debe ser anterior a la fecha de hoy")
  end
end


def edadminima
   if fecha_nacimiento.present? && fecha_nacimiento >= 18.year.ago
        errors.add(:fecha_nacimiento, "debe ser mayor de 18 años")
   end
end




def active_for_authentication?
  super && self.estado
end

def inactive_message
  "Perdon , su cuenta ha sido desactivada"
end



def unique_rut
  self.errors.add(:name, 'Rut ya existente') if Estudiante.where(rut: self.rut).exists?
end




def fullname
  "#{nombre} #{apellidopa} #{apellidoma}" 

end
  






end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout"prueba"
  before_action :set_user, only: [:show,:delete,:edit,:update]
  

  def index
    @users = User.all
  end

  def new
    @user= User.new
    
  end

  def show
    @user= User.find(params[:id])
  end

  def delete
    #@user.destroy
    
    @user.estado = false
    @user.save
        redirect_to users_path, success: "Se ha desvinculado el usuario"
  end


  def update
    
     if @user.update(user_params)
          if @user.rol.descripcion=="Tutor"
             redirect_to tutores_path,success:"Datos Guardados"
          end

          if @user.rol.descripcion!="Tutor"
            redirect_to users_path, success: "Se Actualizaron los datos"
          end
     else
         
            redirect_to edit_user_path, danger: "No se genero el cambio"
          
        

     end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    respond_to do |format| 
    if @user.save
       if @user.rol.descripcion=="Tutor" || @user.rol.descripcion=="Jefe de Carrera"
        format.html {render :edit, success: "Seleccione Carrera"}
        end
        if @user.rol.descripcion=="Administrador" || @user.rol.descripcion=="Sicologo" || @user.rol.descripcion=="Asistente Social" 
        format.html {redirect_to users_path, success: "Se Registro Usuario"}
        end
    
    else
      format.html {render :new}
      end
      end
  end


  private

  def user_params
    params.require(:user).permit(:nombre, :apellidopa, :apellidoma, :rut, :fecha_nacimiento, :facultad_id, :telefono, :email, :password, :password_confirmation, :rol_id, :estado)
    
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_form.html.erb
  <%= simple_form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-info">
          <%= pluralize(@user.errors.count, "Errores") %>
        </div>
        <div class="alert alert-danger">
          <% @user.errors.full_messages.each do |error| %>
            <li> <%= error %> </li>
          <% end %>
        </div>
      <% end %>

        <div class="row">
               <div class="col">

                   <label for="formGroupExampleInput">Nombres </label>
                       <%= f.text_field :nombre, placeholder:"Ej: Monica Catalina" , class:"form-control"  %>
               </div>
       
               <div class="col-md-4">
                     <label for="formGroupExampleInput">Primer Apellido </label>
                           <%= f.text_field :apellidopa, placeholder:"Ej: Perez" , class:"form-control"  %>
               </div>

               <div class="col-md-4">
        
                      <label for="formGroupExampleInput">Segundo Apellido </label>
                           <%= f.text_field :apellidoma, placeholder:"Ej:Perez" , class:"form-control"  %>
               </div>
        </div>
      <br>
              <div class="row">

               <div class="col">
                      <label for="formGroupExampleInput">RUT  </label>
                           <%= f.text_field :rut, placeholder:"Ej: 11.111.111-1" , class:"form-control"  %>
               </div>
         
         
               <div class="col">
                      <label for="formGroupExampleInput">Telefono </label>
                           <%= f.text_field :telefono, placeholder:"Ej: 229325003" , class:"form-control"  %>
               </div>
        
               <div class="col">
       
                           <%= f.label :fecha_nacimiento %><br/>
                           <%= f.date_field :fecha_nacimiento, autofocus: true, class:"form-control" %>
               </div>
        </div>
      <br>
        <div class="row">
              <div class="forminputs"
             <div class="col">
             <label for="formGroupExampleInput">Rol </label>
             <%= f.collection_select :rol_id, Rol.all, :id, :descripcion ,{:include_blank => "Seleccionar Rol"},{class: "btn btn-outline-info btn-sm"}  %>
          
                       
             
                </div>
             
                <div class="col">
                <label for="formGroupExampleInput">Facultad </label>
                  <%= f.collection_select :facultad_id, Facultad.all, :id, :nombrefacultad, {:include_blank => "Seleccionar Facultad"},{class: "btn btn-outline-info btn-sm"}  %>
                </div>
                
               
         </div>

          <div class="col">
              <div class="field">
                           <%= f.label :email %><br/>
                           <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder: "Email" %>
              </div>
           </div>
      <div class="row">
        <div class="col">
        <div class="field">
          <%= f.label :Contraseña %>
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br/>
          <%= f.password_field :password, autocomplete: "off", class:"form-control" , placeholder:"Contraseña"%>
        </div><br>
      </div>
      <div class="col">
        <div class="field">
          <%= f.label :Confirmar_contraseña %><br/>
          <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control", placeholder:"Confirmar contraseña" %>
        </div>
      </div>
     

       

      
      <%= f.submit "Guardar" ,class:"btn btn-info" %> 
      
    <% end %>
  </div>

app/views/users/edit.html.erb
<%= form_for(@user, :html => {:role => 'form'}) do |f| %>
  <%flash.each do |name , msg| %>
    <div class="alert alert-<%= name %>">
      <%= msg %>
    </div>
  <% end %>

 

<div class="form">
  <h1 class="text-center"> Registro de Usuarios</h1>

  <div class="row">

  <div class="col">
  <div class="field">
    <%= f.label :primer_nombre %><br/>
    <%= f.text_field :nombre, autofocus: true, class: "form-control", placeholder: "Primer nombre" %>
  </div><br>
</div>

  <div class="col">
  <div class="field">
    <%= f.label :primer_apellido %><br/>
    <%= f.text_field :apellidopa, autofocus: true, class: "form-control", placeholder: "Primer apellido" %>
  </div>
  </div>
</div>

<div class="row">

    <div class="col">
  <div class="field">
    <%= f.label :segundo_apellido %><br/>
    <%= f.text_field :apellidoma, autofocus: true, class: "form-control", placeholder: "Primer apellido" %>
  </div>
  </div>
</div>
  <div class="row">
    <div class="col">
  <div class="field">
    <%= f.label :rut %><br/>
    <%= f.text_field :rut, autofocus: true, class:"form-control", placeholder: "Rut" %>
  </div><br>
</div>
  <div class="col">
  <div class="field">
    <%= f.label :fecha_nacimiento %><br/>
    <%= f.date_field :fecha_nacimiento, autofocus: true, class:"form-control" %>
  </div>
</div>
  <div class="col">
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder: "Email" %>
  </div>
</div>
</div>

<div class="row">
  
  <div class="col">
<div class="field">
  <%= f.label :celular %><br/>
  <%= f.text_field :telefono, autofocus: true, class: "form-control", placeholder:"Celular" %>
</div>
</div>
</div>
<br>
<div class="row">
  <div class="col">
<div class="field">
  <%= f.label :Tipo_de_usuario %>
  <%= f.collection_select :rol_id, Rol.all, :id, :descripcion ,{:include_blank => "Seleccionar Rol"},{class: "btn btn-outline-info btn-sm"}  %>
 
</div>
</div>





<% if @user.rol.descripcion=="Sicologo" || @user.rol.descripcion=='Asistente Social' %>


<%= f.collection_select :carrera_id, Facultad.where(:estado => true), :id, :nombrefacultad, {:include_blank => "Seleccionar Facultad"},{class: "btn btn-outline-info btn-sm"}  %>



<%end%>


<% if @user.rol.descripcion=="Tutor" || @user.rol.descripcion=='Jefe de Carrera' %>
<div class="col">
<label for="formGroupExampleInput">Carrera: </label>
<%= f.collection_select :carrera_id, Carrera.where(:facultad_id => @user.facultad_id).where(:estado =>true), :id, :nombrecarrera, {:include_blank => "Seleccionar Carrera"},{class: "btn btn-outline-info btn-sm"}  %>
<%end%></div>

<div class="col">
</div>

<div class="col">

 <div class="field">
    <%= f.label "Estado" %> <br />
    <%= f.check_box :estado %> <br />
</div>
</div>

 </div>
  <div class="actions">
    <%= f.submit "Guardar Usuario" ,class:"btn btn-info"%>
  </div>
<% end %>
</div>

app/views/users/index.html.erb
<h1>Profesionales</h1>
<%flash.each do |name , msg| %>
  <div class="alert alert-<%= name %>">
    <%= msg %>
  </div>
<% end %>
<%= link_to 'Agregar Usuario', new_user_path, :class => "btn btn-info" %>

<script src="https://www.w3schools.com/lib/w3.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet" />

<input type="text" id="myInput" onkeyup="buscar()" placeholder="Buscar por nombres...",> 

<table id="myTable" class='table'>
  <thead class="thead-dark">
  <tr>
   <!--When a header is clicked, run the sortTable function, with a parameter, 0 for sorting by names, 1 for sorting by country:-->  
    <th onclick="sortTable(0)"> Nombre </th>
    <th onclick="sortTable(1)"> Rol </th>
    <th onclick="sortTable(2)"> Facultad </th>
    <th onclick="sortTable(3)"> Estado </th>
    <th> Opciones </th>
  </tr>
  </tr>
    <% @users.each do |t| %>
      <% unless t.rol.descripcion.nil? %>
      <% if t.rol.descripcion != "Tutor" %>
  <tr>
    <td><%= t.nombre %> <%= t.apellidopa %> <%=t.apellidoma%></td>
    <% unless t.rol.descripcion.nil? %>
    <td><%= t.rol.descripcion %></td>
    <%end%>
    <td><%= t.facultad.nombrefacultad %></td>
    <td>
  <%if t.estado ==true %>
 <p class= "text-success"> Activo</p> 
 <%else%> 
 <p class="text-danger"> Inactivo</p>
<%end%>
  </td>
    <td>

    <%= link_to 'Mostrar',user_url(t), class:"btn btn-outline-success  btn-sm" %>
    <%= link_to 'Editar', edit_user_url(t), class:"btn btn-outline-warning  btn-sm" %>
    
    <% unless t.estado.nil? %>
    <% if t.estado == true %>
        
      <%= link_to 'Cambiar estado', edit_user_url(t), class: "btn btn-danger btn-sm",
                          method: :delete, data: {confirm: '¿Estas seguro?'} %>
      <% end %>
      <% end %>
  </td>
  </tr>
  <%end%>
  <%end%>
  <%end%>
  </table>

<script>
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("myTable");
  switching = true;
  //Set the sorting direction to ascending:
  dir = "asc"; 
  /*Make a loop that will continue until
  no switching has been done:*/
  while (switching) {
    //start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /*Loop through all table rows (except the
    first, which contains table headers):*/
    for (i = 1; i < (rows.length - 1); i++) {
      //start by saying there should be no switching:
      shouldSwitch = false;
      /*Get the two elements you want to compare,
      one from current row and one from the next:*/
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /*check if the two rows should switch place,
      based on the direction, asc or desc:*/
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          //if so, mark as a switch and break the loop:
          shouldSwitch= true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          //if so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      /*If a switch has been marked, make the switch
      and mark that a switch has been done:*/
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      //Each time a switch is done, increase this count by 1:
      switchcount ++;      
    } else {
      /*If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again.*/
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}

function buscar() {
  // Declare variables
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}

</script>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-9 col-xs-8">
    <h3 class="text-uppercase">Crear Usuario  <%= link_to 'Atrás', users_path, :class => "btn btn-info btn-sm" %></h3>
   
    </div>
</div>
<div>
  <%= render 'form' %>
</div>
<br><br>

app/views/users/show.html.erb
      
      <h1 class= "text-info"><u> Datos Usuario </u> </h1> 
      
      <p>Nombre : <%= @user.nombre %> <%= @user.apellidopa%> <%= @user.apellidoma%> </p>
      <p>Rut: <%= @user.rut %></p>
      <p>Fecha de Nacimiento: <%= @user.fecha_nacimiento %></p>
      
    
      <p>Rol: <%= @user.rol.descripcion %></p>
      
      <p>Facultad: <%= @user.facultad.nombrefacultad %>
      <p>Telefono: <%= @user.telefono %></p>


      <%= link_to '<== Volver', users_path, :class => "btn btn-info btn-lg" %></h3> 