config/routes.rb
Rails.application.routes.draw do
  devise_for :users  , :path_prefix => 'my', :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'login', to: 'devise/session#new'
  end
  resources :users
  delete 'users/:id/edit', to: 'users#delete'
 
  get 'informes/index'
  get 'informes/new'
  resources :informacion
  resources :facultads
  delete 'facultads/:id/edit', to: 'facultads#delete'
  resources :alertas
  resources :estudiantes
  delete 'estudiantes/:id/edit', to: 'estudiantes#delete'
  resources :informes
  delete 'informes/:id/edit', to: 'informes#delete'
  resources :rols
  resources :tutores
  delete 'tutores/:id/edit', to: 'tutores#delete'
  resources :carreras
  delete 'carreras/:id/edit', to: 'carreras#delete'
  resources :page

  

  devise_scope :user do
    authenticated :user do
      root 'page#index', as: :authenticated_root
    end
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end



  




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/facultad.rb
class Facultad < ApplicationRecord
    has_many :carreras
    has_many :users
    validates :nombrefacultad, :presence => true,length: {minimum:3,maximum: 50 },uniqueness: true
end

app/controllers/facultads_controller.rb
class FacultadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_facultad, only: [:show,:delete,:edit,:update]

  layout "prueba"
  def index
    @facultades=Facultad.all
    @facultads= Facultad.new
  end

  def show
    @facultad= Facultad.find(params[:id])
  end 
  
  def delete
    #@user.destroy
    
    @facultad.estado = false
    @facultad.save
      redirect_to facultads_path, success: "Facultad no existente"
  end
  
  def update
      if @facultad.update(facultad_params)
        redirect_to facultad_path, success: "Se Actualizaron los datos"
      else
        render :edit , danger: "Modifique por valores válidos"
      end
  end

  def edit
  end
   

  def new
   @facultads= Facultad.new
  end

  def create
    @facultad= Facultad.new(facultad_params)
    if @facultad.save
      redirect_to facultads_path, success: "Se creo correctamente"
    else
    render 'new' ,danger:"Ingrese datos Validos"
    end
  end
  

  private
    def facultad_params
      params.require(:facultad).permit(:nombrefacultad, :estado)
    end

    def set_facultad
      @facultad = Facultad.find(params[:id])
    end


  end

app/views/facultads/edit.html.erb
<%= form_for(@facultad, :html => {:role => 'form'}) do |f| %>
  
  <div class="form">
    <h1 class="text-center"> Actualizacion de Facultad</h1>
  
    <div class="row">
  
    <div class="col">
    <div class="field">
      <%= f.label :nombrefacultad %><br/>
      <%= f.text_field :nombrefacultad, autofocus: true, class: "form-control", placeholder: "Nombre" %>
    </div><br>
  </div>
  
  
  <div class="col">
  
   <div class="field">
      <%= f.label "Estado" %> <br />
      <%= f.check_box :estado %> <br />
  </div>
  </div>
  
   </div>
    <div class="actions">
      <%= f.submit "Guardar Facultad" ,class:"btn btn-success"%>
    </div>
  <% end %>
  </div>

app/views/facultads/index.html.erb
<h1> Facultades </h1>



<%= link_to 'Agregar Facultad', new_facultad_path, :class => "btn btn-info " %>

<script src="https://www.w3schools.com/lib/w3.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet" />

<input type="text" id="myInput" onkeyup="buscar()" placeholder="Buscar por nombres...",> 

<table id="myTable" class='table'>
  <thead class="thead-dark">
  <tr>
   <!--When a header is clicked, run the sortTable function, with a parameter, 0 for sorting by names, 1 for sorting by country:-->  
    <th onclick="sortTable(0)">Nombre</th>
    <th onclick="sortTable(1)">Estado</th>
    <th onclick="sortTable(2)">Fecha</th>
    <th> Opciones </th>
  </tr>
  </tr>
    <% @facultades.each do |t| %>
  <tr>
    <td><%= t.nombrefacultad %></td>
    <td class="text-success">
      <%if t.estado ==true %>
      Activo 
     <%else%> 
      Inactivo
    <%end%>
     </td>    
    <td><%= t.created_at %></td>
<td>


    <%= link_to 'Mostrar', facultad_url(t), class:"btn btn-outline-success  btn-sm" %>
   
     
     
    <%= link_to 'Editar', edit_facultad_url(t), class:"btn btn-outline-warning  btn-sm" %>




    <% unless t.estado.nil? %>
    <% if t.estado == true %>
        
      <%= link_to 'Cambiar estado', edit_facultad_url(t), class: "btn btn-danger btn-sm",
                          method: :delete, data: {confirm: '¿Estas seguro?'} %>
      <% end %>
      <% end %>
      </td>
      </tr>
  <% end %>
</table>

<script>
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("myTable");
  switching = true;
  //Set the sorting direction to ascending:
  dir = "asc"; 
  /*Make a loop that will continue until
  no switching has been done:*/
  while (switching) {
    //start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /*Loop through all table rows (except the
    first, which contains table headers):*/
    for (i = 1; i < (rows.length - 1); i++) {
      //start by saying there should be no switching:
      shouldSwitch = false;
      /*Get the two elements you want to compare,
      one from current row and one from the next:*/
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /*check if the two rows should switch place,
      based on the direction, asc or desc:*/
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          //if so, mark as a switch and break the loop:
          shouldSwitch= true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          //if so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      /*If a switch has been marked, make the switch
      and mark that a switch has been done:*/
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      //Each time a switch is done, increase this count by 1:
      switchcount ++;      
    } else {
      /*If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again.*/
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}

function buscar() {
  // Declare variables
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}

</script>

app/views/facultads/new.html.erb
 <h3 class="text-uppercase">Crear Facultad  <%= link_to '<= Volver', facultads_path, :class => "btn btn-info-3 btn-sm" %></h3></h1>

<%=form_for(@facultads) do |f| %>

  <div class="form-group">
    <label for="formGroupExampleInput"></label>
    <%= f.text_field :nombrefacultad, placeholder:"Nombre Facultad" , class:"form-control"  %>
    
  </div>

   <%= f.submit "Guardar" ,class:"btn btn-info" %> 
 
  <%end%>

app/views/facultads/show.html.erb
<h1 class= "text-info"><u> Datos Carrera </u> </h1> 
<br>


<p>Nombre: <%= @facultad.nombrefacultad %></p>

<%= link_to '<== Volver', facultads_path, :class => "btn btn-info btn-lg" %></h3> 